### ISSUE TITLE
TDD or BDD?

### ISSUE THREAD

**Issue by baishali-ghosh** [code-paw/bling-souq#7]
I would like to make this project test driven, include unit tests and integration as well. What do you think?  Shall we follow TDD or write tests later?

**Comment by kunagpal** [comment]
TDD serves us little conceivable benefit here, as we are not writing code for tests, not so much as writing tests for code. Instead of running after the task of fixing breaking tests for erstwhile blank code, we would do ourselves a world of good by writing code to suit a given set of intents and purposes, followed by writing tests for the previously written code.

**Comment by baishali-ghosh** [comment]
Alright
